// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: markdownsvc/v1/markdown.proto

package markdownsvcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkdownService_ParseMarkdown_FullMethodName = "/markdownsvc.v1.MarkdownService/ParseMarkdown"
	MarkdownService_RenderToHTML_FullMethodName  = "/markdownsvc.v1.MarkdownService/RenderToHTML"
	MarkdownService_ChunkMarkdown_FullMethodName = "/markdownsvc.v1.MarkdownService/ChunkMarkdown"
	MarkdownService_TransformAST_FullMethodName  = "/markdownsvc.v1.MarkdownService/TransformAST"
)

// MarkdownServiceClient is the client API for MarkdownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarkdownService provides markdown processing capabilities using the remark/unified ecosystem.
type MarkdownServiceClient interface {
	// ParseMarkdown is the primary endpoint: parse to AST, optionally render HTML and/or apply transforms.
	ParseMarkdown(ctx context.Context, in *ParseMarkdownRequest, opts ...grpc.CallOption) (*ParseMarkdownResponse, error)
	// RenderToHTML is a convenience endpoint that returns just HTML, no AST.
	RenderToHTML(ctx context.Context, in *RenderToHTMLRequest, opts ...grpc.CallOption) (*RenderToHTMLResponse, error)
	// ChunkMarkdown performs semantic chunking for RAG pipelines.
	ChunkMarkdown(ctx context.Context, in *ChunkMarkdownRequest, opts ...grpc.CallOption) (*ChunkMarkdownResponse, error)
	// TransformAST applies transforms to an existing AST (avoids re-parsing).
	TransformAST(ctx context.Context, in *TransformASTRequest, opts ...grpc.CallOption) (*TransformASTResponse, error)
}

type markdownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkdownServiceClient(cc grpc.ClientConnInterface) MarkdownServiceClient {
	return &markdownServiceClient{cc}
}

func (c *markdownServiceClient) ParseMarkdown(ctx context.Context, in *ParseMarkdownRequest, opts ...grpc.CallOption) (*ParseMarkdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseMarkdownResponse)
	err := c.cc.Invoke(ctx, MarkdownService_ParseMarkdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markdownServiceClient) RenderToHTML(ctx context.Context, in *RenderToHTMLRequest, opts ...grpc.CallOption) (*RenderToHTMLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderToHTMLResponse)
	err := c.cc.Invoke(ctx, MarkdownService_RenderToHTML_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markdownServiceClient) ChunkMarkdown(ctx context.Context, in *ChunkMarkdownRequest, opts ...grpc.CallOption) (*ChunkMarkdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkMarkdownResponse)
	err := c.cc.Invoke(ctx, MarkdownService_ChunkMarkdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markdownServiceClient) TransformAST(ctx context.Context, in *TransformASTRequest, opts ...grpc.CallOption) (*TransformASTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformASTResponse)
	err := c.cc.Invoke(ctx, MarkdownService_TransformAST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkdownServiceServer is the server API for MarkdownService service.
// All implementations must embed UnimplementedMarkdownServiceServer
// for forward compatibility.
//
// MarkdownService provides markdown processing capabilities using the remark/unified ecosystem.
type MarkdownServiceServer interface {
	// ParseMarkdown is the primary endpoint: parse to AST, optionally render HTML and/or apply transforms.
	ParseMarkdown(context.Context, *ParseMarkdownRequest) (*ParseMarkdownResponse, error)
	// RenderToHTML is a convenience endpoint that returns just HTML, no AST.
	RenderToHTML(context.Context, *RenderToHTMLRequest) (*RenderToHTMLResponse, error)
	// ChunkMarkdown performs semantic chunking for RAG pipelines.
	ChunkMarkdown(context.Context, *ChunkMarkdownRequest) (*ChunkMarkdownResponse, error)
	// TransformAST applies transforms to an existing AST (avoids re-parsing).
	TransformAST(context.Context, *TransformASTRequest) (*TransformASTResponse, error)
	mustEmbedUnimplementedMarkdownServiceServer()
}

// UnimplementedMarkdownServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkdownServiceServer struct{}

func (UnimplementedMarkdownServiceServer) ParseMarkdown(context.Context, *ParseMarkdownRequest) (*ParseMarkdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseMarkdown not implemented")
}
func (UnimplementedMarkdownServiceServer) RenderToHTML(context.Context, *RenderToHTMLRequest) (*RenderToHTMLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderToHTML not implemented")
}
func (UnimplementedMarkdownServiceServer) ChunkMarkdown(context.Context, *ChunkMarkdownRequest) (*ChunkMarkdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkMarkdown not implemented")
}
func (UnimplementedMarkdownServiceServer) TransformAST(context.Context, *TransformASTRequest) (*TransformASTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformAST not implemented")
}
func (UnimplementedMarkdownServiceServer) mustEmbedUnimplementedMarkdownServiceServer() {}
func (UnimplementedMarkdownServiceServer) testEmbeddedByValue()                         {}

// UnsafeMarkdownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkdownServiceServer will
// result in compilation errors.
type UnsafeMarkdownServiceServer interface {
	mustEmbedUnimplementedMarkdownServiceServer()
}

func RegisterMarkdownServiceServer(s grpc.ServiceRegistrar, srv MarkdownServiceServer) {
	// If the following call panics, it indicates UnimplementedMarkdownServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkdownService_ServiceDesc, srv)
}

func _MarkdownService_ParseMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseMarkdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownServiceServer).ParseMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownService_ParseMarkdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownServiceServer).ParseMarkdown(ctx, req.(*ParseMarkdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkdownService_RenderToHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderToHTMLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownServiceServer).RenderToHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownService_RenderToHTML_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownServiceServer).RenderToHTML(ctx, req.(*RenderToHTMLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkdownService_ChunkMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkMarkdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownServiceServer).ChunkMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownService_ChunkMarkdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownServiceServer).ChunkMarkdown(ctx, req.(*ChunkMarkdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkdownService_TransformAST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformASTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownServiceServer).TransformAST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownService_TransformAST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownServiceServer).TransformAST(ctx, req.(*TransformASTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkdownService_ServiceDesc is the grpc.ServiceDesc for MarkdownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkdownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "markdownsvc.v1.MarkdownService",
	HandlerType: (*MarkdownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseMarkdown",
			Handler:    _MarkdownService_ParseMarkdown_Handler,
		},
		{
			MethodName: "RenderToHTML",
			Handler:    _MarkdownService_RenderToHTML_Handler,
		},
		{
			MethodName: "ChunkMarkdown",
			Handler:    _MarkdownService_ChunkMarkdown_Handler,
		},
		{
			MethodName: "TransformAST",
			Handler:    _MarkdownService_TransformAST_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "markdownsvc/v1/markdown.proto",
}
